baseURL = 'https://haidangcodes.github.io/MyBlog/'

languageCode = 'vi-vn'
title = 'Blog Láº­p TrÃ¬nh Máº¡ng | Tráº§n Háº£i ÄÄƒng'
theme = "PaperMod"

[params]
    env = "production"
    title = "Blog Láº­p TrÃ¬nh Máº¡ng"
    author = "Tráº§n Háº£i ÄÄƒng"
    description = "Chia sáº» kiáº¿n thá»©c Java & JavaScript chuyÃªn sÃ¢u"
    
    # KÃ­ch hoáº¡t giao diá»‡n cÄƒn giá»¯a vÃ  cÃ¡c tÃ­nh nÄƒng phá»¥
    ShowReadingTime = true
    ShowCodeCopyButtons = true
    defaultTheme = "auto"
    disableThemeToggle = false

    [params.homeInfoParams]
        Title = "ChÃ o má»«ng Ä‘áº¿n vá»›i Blog cá»§a ÄÄƒng! ğŸ‘‹"
        Content = "NÆ¡i tá»•ng há»£p kiáº¿n thá»©c vá» **Láº­p trÃ¬nh máº¡ng**, táº­p trung vÃ o **Java** vÃ  **JavaScript**."

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 20

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 30

